name: Build Flet APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build APK
        run: |
          pip install --upgrade pip
          pip install flet groq
          # أمر سحري لتغيير اسم الحزمة في ملفات الإعدادات قبل البناء
          flet build apk --name "AlOmran" --org "com.alomran" --yes
          
      - uses: actions/upload-artifact@v4
        with:
          name: AlOmran-APK
          path: build/apk/*.apk
